### ISSUE TITLE
HTML content

### ISSUE THREAD

**Issue by Elisarmor** [Elisarmor/counter#3]
Create a UI that looks like this:  (_Center it on larger screens._)
![screen shot 2019-02-12 at 8 32 44 pm](https://user-images.githubusercontent.com/45398751/52682533-6e193b00-2f05-11e9-9a7c-302ddcc72505.png)

The list items that you see are to be inserted by the JS from an array.  You can use an example similar to this for testing: 
```
[
    {
        "id": "273489572134897510243",
        "name": "Push-ups",
        "color": "red",
        "goal": 500,
        "current": 250
    },
    {
        "id": "287345234527347234732",
        "name": "Pull-ups",
        "color": "green",
        "goal": 10,
        "current": 5
    },
    {
        "id": "898979802734895723477",
        "name": "Sit-ups",
        "color": "blue",
        "goal": 20,
        "current": 21
    }
]
```

When you click on one of the bars, call an empty function, the content of that function to be added later.

**Comment by Jmooring12** [comment]
@Elisarmor What Does Center it on larger screens mean?

**Comment by Elisarmor** [comment]
[https://memorizetext.com/#/home](https://memorizetext.com/#/home)

See how the main part of the page is centered because it would look weird if it took up the whole width?

**Comment by Jmooring12** [comment]
@Elisarmor Could you send me the color codes eg.#00000?

**Comment by Elisarmor** [comment]
Be sure to do all this in a different file, say `home.html`.

**Comment by Jmooring12** [comment]
What about `index.html`?

**Comment by Elisarmor** [comment]
Nope.  It must be a different file without the `html`, `head`, and `body` tags.
